version: "3.8"
services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  web:
    image: vscav/sos-tag-api:beta
    depends_on:
      - redis
    ports: 
      - "8080:8080"